### ISSUE TITLE
problem when grad backward

### ISSUE THREAD

**Issue by lixincheng4026** [krrish94/chamferdist#1]
Thanks for your work, I have used your code for pytorch to evaluate two points set,but problems happened when  I want the dist to backward.
TypeError: backward() takes 3 positional arguments but 5 were given.
Really dont know what happened.

**Comment by sawadika213** [comment]
I have the same problem ? Do you have solved?

**Comment by krrish94** [comment]
Yes, that's a bug indeed! Should be fixed with https://github.com/krrish94/chamferdist/commit/1158a98bb4bb8e5b9d4f3415d9936b2dcddf9831

The latest `master` branch fixes this issue, and so does the pypi package (version `0.3.0` or higher).
