### ISSUE TITLE
Ability to return non-reduced Chamfer loss

### ISSUE THREAD

**Issue by haritha-j** [krrish94/chamferdist#16]
Hey, thanks for the repo, I've found it quite useful. One feature I've needed is the ability to return chamfer loss for each point cloud pair, rather than a reduced version through 'mean' or 'sum'. This was already present in the pytorch3D version. 

I was hoping you could add this back as I think it would be rather useful, and it only requires loosening the validation to add back the functionality. I'll be happy to just submit a PR from my fork if you think this would be a useful addition.

**Comment by krrish94** [comment]
Hi @haritha-j , thanks for opening this -- sure, happy to have you open a PR

**Comment by kuaitoukid** [comment]
> Hey, thanks for the repo, I've found it quite useful. One feature I've needed is the ability to return chamfer loss for each point cloud pair, rather than a reduced version through 'mean' or 'sum'. This was already present in the pytorch3D version.
> 
> I was hoping you could add this back as I think it would be rather useful, and it only requires loosening the validation to add back the functionality. I'll be happy to just submit a PR from my fork if you think this would be a useful addition.

Maybe it's better to comment https://github.com/krrish94/chamferdist/blob/master/chamferdist/chamfer.py from L102 to L104 :>)

**Comment by krrish94** [comment]
A PR implementing this functionality was merged last month: https://github.com/krrish94/chamferdist/pull/17/commits/db341685c648ccc0e50613aafa337a5ebb57e545
