### ISSUE TITLE
error when print(idx1)

### ISSUE THREAD

**Issue by Leerw** [krrish94/chamferdist#2]
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-23-a4beaff4bff8> in <module>()
----> 1 print(idx1)

4 frames
/usr/local/lib/python3.6/dist-packages/torch/tensor.py in __repr__(self)
    128         # characters to replace unicode characters with.
    129         if sys.version_info > (3,):
--> 130             return torch._tensor_str._str(self)
    131         else:
    132             if hasattr(sys.stdout, 'encoding'):

/usr/local/lib/python3.6/dist-packages/torch/_tensor_str.py in _str(self)
    309                 tensor_str = _tensor_str(self.to_dense(), indent)
    310             else:
--> 311                 tensor_str = _tensor_str(self, indent)
    312 
    313     if self.layout != torch.strided:

/usr/local/lib/python3.6/dist-packages/torch/_tensor_str.py in _tensor_str(self, indent)
    207     if self.dtype is torch.float16 or self.dtype is torch.bfloat16:
    208         self = self.float()
--> 209     formatter = _Formatter(get_summarized_data(self) if summarize else self)
    210     return _tensor_str_with_formatter(self, indent, formatter, summarize)
    211 

/usr/local/lib/python3.6/dist-packages/torch/_tensor_str.py in __init__(self, tensor)
     81         if not self.floating_dtype:
     82             for value in tensor_view:
---> 83                 value_str = '{}'.format(value)
     84                 self.max_width = max(self.max_width, len(value_str))
     85 

/usr/local/lib/python3.6/dist-packages/torch/tensor.py in __format__(self, format_spec)
    375     def __format__(self, format_spec):
    376         if self.dim() == 0:
--> 377             return self.item().__format__(format_spec)
    378         return object.__format__(self, format_spec)
    379 

RuntimeError: CUDA error: an illegal memory access was encountered

**Comment by krrish94** [comment]
Closing; inactivity.
