### ISSUE TITLE
Fail to install.

### ISSUE THREAD

**Issue by SkyeFromKindergarten** [krrish94/chamferdist#3]
Hi~ I find this work really will solve my problem.But I failed when installing.

When I use pip to install, it comes up like below.
![image](https://user-images.githubusercontent.com/37540879/71151844-badd4900-226f-11ea-8db4-64a02b57191c.png)

When I install with source code, it comes nvcc fatal
`nvcc fatal   : Unsupported gpu architecture 'compute_75'
error: command '/usr/local/cuda-9.0/bin/nvcc' failed with exit status 1
`
But Im sure my cuda works fine. Can you please tell me where it maybe wrong?

System information: Ubuntu 16.04  python3.6  pytorch1.3

**Comment by WhynotBicycle** [comment]
The same issue, what I currently know is I have 'fatal error: ATen/ATen.h: No such file or directory' when run the chamferdist.cu independently. It means I don't have ATen though my PyTorch is 1.4.0.

I'm trying to reinstall PyTorch from source now.

**Comment by krrish94** [comment]
Could you check `torch.cuda.is_available()` first? If you're able to run pytorch code on CUDA, then a fix of this sort could help (See https://github.com/NVIDIAGameWorks/kaolin/issues/31#issuecomment-557776519)

Also, curious: what GPU archs are you using? Newer RTX 2080Ti etc? (I'm looking to update the package to suit those archs)

**Comment by hugovergnes** [comment]
Same problem here.
Sure my cuda works fine, and torch.cuda.is_available() returns True. 
I installed it with pip, but even though it's in my conda environment (conda list). 
I cannot import it.

**Comment by krrish94** [comment]
I tried reinstalling this today (PyTorch 1.6) and it works fine. Closing for now, but feel free to reopen this if anything.

**Comment by toobaimt** [comment]
Exactly the same issue installing on Windows10, python 3.8, pytorch 1.6
